services:
  - type: web
    name: visualiser
    env: node
    buildCommand: cd src && npm install
    startCommand: cd src && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /api/health 