services:
  - type: web
    name: visualiser
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://visualiser-xhjh.onrender.com
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - render.yaml
    buildOptimization: true 