services:
  - type: web
    name: visualiser
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /api/health 